[package]
name = "rebuilder"
version = "0.1.0"
authors = ["Jelle van der Waa <jelle@archlinux.org>"]
edition = "2018"
description = "A CLI tool to determine the rebuild order of provided package(s)."
documentation = "https://gitlab.archlinux.org/archlinux/rebuilder"
readme = "README.md"
homepage = "https://gitlab.archlinux.org/archlinux/rebuilder"
repository = "https://gitlab.archlinux.org/archlinux/rebuilder"
license-file = "LICENSE"
keywords = ["archlinux", "build", "alpm"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
alpm = "0.10"
petgraph = "0.5"
structopt = "0.3"

[dev-dependencies]
rstest = "0.6"
tar = "0.4"
tempfile = "3"
flate2 = "1.0"


[profile.release]
lto = true
codegen-units = 1
