[package]
name = "rebuilder"
version = "0.1.0"
authors = ["Jelle van der Waa <jelle@archlinux.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "0.9.0"
anyhow = "1"
structopt = "0.3"
petgraph = "0.5.0"

[dev-dependencies]
tar = "0.4"

[profile.release]
opt-level = 3
lto = true
